name: Update README with Currency Rates

on:
  schedule:
    - cron: "0 * * * *" # run every hour
  workflow_dispatch: # accept manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest # standard version of Ubuntu Linux

    steps:
      # Get source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch currency rates
      - name: Fetch currency rates
        env:
          API_KEY: ${{ secrets.OPENEXCHANGE_API_KEY }}
        run: |
          curl -s "https://openexchangerates.org/api/latest.json?app_id=$API_KEY" -o rates.json

      # Update README.md
      - name: Update README.md
        run: |
          # Extract currency rates
          RATE_USD_VND=$(jq '.rates.VND / .rates.USD' rates.json)
          RATE_USD_EUR=$(jq '.rates.EUR / .rates.USD' rates.json)
          RATE_EUR_VND=$(jq '.rates.VND / .rates.EUR' rates.json)

          # Update currency rates in README.md
          sed -i "s/| USD to VND     | .* |/| USD to VND     | \`$RATE_USD_VND\` |/" README.md
          sed -i "s/| USD to EUR     | .* |/| USD to EUR     | \`$RATE_USD_EUR\` |/" README.md
          sed -i "s/| EUR to VND     | .* |/| EUR to VND     | \`$RATE_EUR_VND\` |/" README.md
          sed -i "s|Last updated: .*|Last updated: $(date '+%Y-%m-%d %H:%M:%S')|g" README.md

          # Configure Git
          git config --global user.name "anvng"
          git config --global user.email "anvndev@gmail.com"

          # Commit changes if any
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update currency rates"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
          fi

      # Clean up temporary files
      - name: Clean up
        run: rm rates.json
